version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
          source_dir: orb
      - orb-tools/pack:
          filters: *filters
          source_dir: orb
      - orb-tools/review:
          exclude: RC009,RC010
          filters: *filters
          source_dir: orb
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
          filters: *filters
      - orb-tools/publish:
          orb_name: jetbrains/qodana
          vcs_type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          orb_name: jetbrains/qodana
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
