blank_issues_enabled: false
contact_links:
  - name: Report a problem
    url: https://jb.gg/qodana-issue
    about: Report a bug to Qodana team.
  - name: Give your feedback
    url: https://jb.gg/qodana-slack
    about: Share your feedback with the Qodana team on our Slack.
