name: Sync branches

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    name: Update latest branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          force: false
