name: Qodana - Code Inspection

on:
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/work/qodana-cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2.0-eap

#     Changes permissions of files in the cache folder in case of permissions issues during post-cache task
      - name: Change cache folder permissions
        run: sudo chmod -R 555 /home/runner/work/qodana-cache
